// import ApiCallInterval from "../models/apiCallIntervalModel";

export const STATUS = {
  SUCCESS: "Success",
  ERROR: "Error",
  UNAUTHORIZED: "Unauthorized",
  FORBIDDEN: "Forbidden",
  FAILED: "Failed",
  NOT_FOUND: "Not Found",
};

export const STATUS_CODE = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
  TOO_MANY_REQUEST: 429,
};

export const MESSAGES = {
  USER: {
    CREATED: "User created successfully",
    NOT_FOUND: "User not found",
    DELETED: "User deleted successfully",
    USER_ALREADY_EXISTS: "User already exists",
    DUPLICATE_USER: "Duplicate User",
    RESET_PASSWORD: "Password reset successfully",
    RESET_PASSWORD_FAIL: "Reset password failed",
    NEW_PASSWORD_REQUIRED: "New password needed",
    INVALID_USER: "Invalid user",
    EMAIL_USE: "Email already in use",
    DUPLICATE_EMAIL: "Duplicate email",
    PHONE_USE: "Phone already in use",
    DUPLICATE_PHONE: "Duplicate mobile",
    PROFILE_UPDATE: "Profile updated successfully",
    REGISTRATION_MESSAGE: "Registration successful, please verify OTP",
    RESET: "Reset your Booking Cabs password",
    MOBILE_EMAIL_DUPLICATE:
      "User with this email, mobile, and role already exists",
    USERALREADYEXISTS: "This User already exists",
    OLD_PASSWORD: "Old password is incorrect",
    CHANGE_PASSWORD_FAIL: "Change Password has been failed",
    CHANGE_PASSWORD: "Your password was successfully changed",
    OLD_AND_NEW_PASSWORD_REQUIRED: "Old and new password are required",
    PHONE_OR_EMAIL_REQUIRED: "Phone or email required for the guest login",
    MISSING_CONTACT: "Contact is missing please use phone or email",
    USER_ALREADY_VERIFIED: "User is already verified. OTP resend not required",
    USER_DELETED: "User Deleted successfully",
    USER_PROFILE_NOT_FOUND: "User profile not found",
    PROFILE_CREATED: "User profile created successfully",
    LOGIN_HISTORY: "Login history fetched",
    LOGIN_HISTORY_ALL_USER: "All user login histories fetched",
    LOGIN_HISTORY_NOT_FOUND: "No login history found for this user",
    LOGIN_STATUS: "Here is the user login history details",
    ACTIVE_USER: "Successfully retrieved active users",
    NO_ACTIVE_USER: "No active users found",
    EMAIL_ALT_EMAIL_NOT_SAME: "Email and Alternate Email cannot be the same.",
    USER_ACTIVATED: "User activated successfully",
    USER_PREF_CITY: "Preferred cities added successfully",
    USER_LANG_UPDATED: "User Lang updated successfully",
    USER_PACKAGE_ID: "User package id is mandatory.",
    GCM_ID_NOT_FOUND: "No user found or GCM ID not changed",
    USER_LOGGEDIN_STATUS:"User logged in status.",
    USER_STATUS_UPDATE:"User ststus updated successfully.",
    COMBINATION_AVAILABLE:"User with this email/mobile and type available."
  },
  FARE: {
    ADDED: "Fare Added Successfully",
    UPDATED: "Fare Updated Successfully",
  },
  AUTH: {
    UNAUTHORIZED: "You are unauthorized please verify your credential again.",
    INVALID_TOKEN: "Invalid token",
    LOGIN_SUCCESS: "Login successful",
    MISSING_FIELD: "For login email and password mandatory",
    INVALID_PASSWORD: "Invalid Password",
    TOKEN_MISSING: "Token is missing please, add token",
    EMAIL_REQUIRED: "Email is required",
    PHONE_REQUIRED: "Phone number is required",
    MISSING_PHONE: "Missing mobile",
    OTP_VERIFIED: "OTP verified successfully",
    INVALID_OTP: "Invalid or expired OTP",
    OTP_VERIFICATION: "OTP Verification Failed",
    OTP: "OTP sent successfully",
    RESET: "Reset link sent to your email",
    PASSWORD_CONFIRM: "Password and confirm password not match",
    CHECK_PASSWORD: "Please check the password again.",
    OTP_CODE: "Your OTP code",
    USER_ROLE: "User with this role not found",
    PASSWORD_CHANGE: "New password cannot be the same as the old password.",
    LOGOUT_SUCCESSFULLY: "Logout successful",
    USER_INACTIVE: "Your account is in-active, please discuss with your admin",
    MOBILE_VERFICATION: "Mobile verification",
    RECAPTCHA_VERIFICATION: "Recaptcha verification failed",
    EMAIL_SEND: "Email send to user.",
    ACCOUNT_ACTIVATION: "Account Staus Email",
    SMS_API_NOT_CONFIGURED:"SMS API configuration not found",
    EMAIL_VERFICATION:"Email verification link and signup detail."
  },
  BANK: {
    BANK_UPDATED: "Bank account updated successfully",
    BANK_NOT_FOUND: "Bank account not found",
    BANK_DELETED: "Bank account soft-deleted",
    BANK_DETAIL: "Bank detail added successfully",
  },
  COMPANY: {
    COMPANY_UPDATED: "Company detail updated successfully",
    COMPANY_NOT_FOUND: "Company not found",
    COMPANY_DELETED: "Company detail soft-deleted",
    COMPANY_DETAIL: "Company detail added successfully",
    COMPANY_DETAIL_FETCHED: "Company detail fetched successfully",
  },
  ROLE: {
    ROLE_ID_NOT_PROVIDED: "Role ID not provided",
    INVALID_ROLE: "Invalid Role",
    ACCESS_DENIED: "Access Denied",
  },
  GENERAL: {
    SOMETHING_WENT_WRONG: "Something went wrong",
    TOO_MANY_REQUEST: "Too many requests, please try again later",
    MANDATORY_FIELD: "Please fill mandatory fields before proceeding",
    NOT_FOUND: "Not found.",
    DATA_ADDED: "Data Added successfully",
    DATA_UPDATED: "Data Updated successfully",
    DATA_DELETED: "Data Deleted successfully",
    DATA_CREATED: "Data Created successfully",
    DATA_FETCHED: "Data fetched successfully",
    RECORD_NOT_FOUND: "Record not found",
    USER_ID_MANDATORY: "User ID is mandatory",
    NO_DATA_FOUND: "No data found",
    INVALID_COLUMN_NAME: "Invalid column name",
    INVALID_COMMENT: "Invalid commenter type. Must be 'client' or 'driver'.",
    DATA_NOT_VALID: "Invalid Data",
    THANK_YOU: "Thanks for submission, we’ll update approval soon.",
    ERROR_WHILE_UDPATE: "Ohh, there is an error while updateing the data",
    INVOICE_SENT: "Invoice sent successfully",
    FILE_MANDATORY: "File is mandatory",
    FILE_UPLOADED: "File uploaded successfully",
    DATA_INSERTED: "Data inserted successfully",
    EMAIL_SENT: "Email/Message sent to user",
    MESSAGES_SENT: "Message sent to user",
    MESSAGE_NOT_SENT:"Message could not be sent.",
    EMAIL_NOT_SENT: "Email could not be sent",
  },
  DOCUMENT: {
    UPLOADED: "Document uploaded successfully",
    UPLOAD_FAILED: "Document upload failed",
    FAILED_FETCH: "Failed to fetch documents",
    FAILED_TO_FETCH_PENDING: "Failed to fetch pending documents",
    UPDATED: "Document updated successfully",
    NOT_FOUND: "Document not found",
    FETCHED: "Document fetched successfully",
  },
  REFERRAL: {
    INVALID_REFERRAL_CODE: "Invalid referral code",
    REFERRAL_CODE_NOT_FOUND: "Referral code not found",
    REFERRAL_CODE_ALREADY_USED: "Referral code already used",
    REFERRAL_CODE_USED: "Referral code used successfully",
  },
  CREATED_LIMIT: {
    CREATED_LIMIT: "Created limit successfully fetched",
    LIMIT_NOT_FOUND: "Limit not found",
    LIMIT_DELETED: "Limit soft-deleted",
    LIMIT_UPDATED: "Limit updated successfully",
    LIMIT_STATUS_UPDATED: "Limit status updated successfully",
    LIMIT_DETAIL: "Limit detail added successfully",
  },
  WALLET: {
    WALLET_ADDED: "Wallet added successfully",
    WALLET_NOT_FOUND: "Wallet not found",
    WALLET_DELETED: "Wallet soft-deleted",
    WALLET_DETAIL: "Wallet detail added successfully",
    WALLET_UPDATED: "Wallet updated successfully",
    INSUCIENT_BALANCE: "Insufficient balance",
  },
  DRIVER: {
    DRIVER_ADDED: "Driver added successfully",
    DRIVER_NOT_FOUND: "Driver not found",
    DRIVER_DELETED: "Driver soft-deleted",
    DRIVER_DETAIL: "Driver detail added successfully",
    DRIVER_UPDATED: "Driver updated successfully",
    ONLINE_DRIVER_STATUS: "Here is the driver online status",
    Api_Call_Interval: "Api call interval fetched successfully",
    Api_Call_Interval_Not_Found: "Api call interval not found",
    SEQUENTIAL: "Driver sequential status fetched successfully",
    DRIVER_ACCEPTED_JOB: "Here is the driver accepted job",
    CAB_TYPE_MACHED: "Cab type matched successfully",
    VEHICLE_DETAILS_FETCHED: "Vehicle details fetched successfully",
    VEHICLE_TYPE_NOT_FOUND: "Vehicle type not found",
    DRIVER_FUTURE_ACCEPTED_JOB: "Here is the driver future accepted job",
    DRIVER_STARTED_TRIP: "Driver started trip successfully",
    DRIVER_ENDED_TRIP: "Driver ended trip successfully",
    DRIVER_STARTED_TRIP_NOT_FOUND: "Driver started trip not found",
    DRIVER_ENDED_TRIP_NOT_FOUND: "Driver ended trip not found",
    DRIVER_STARTED_TRIP_FAILED: "Driver started trip failed",
    DRIVER_LOCATION: "Driver location added successfully",
    DRIVER_BOOKING_ALLOCATION_SUCCESSFULLY:
      "Driver booking allocation successfully",
    ACTIVE_DRIVER: "Here is the active driver list.",
    INVALID_DRIVER_ID: "Invalid driver ID",
    WAYPOINT: "Waypoints fetched successfully",
    PICKUP_LOCATION_NOT_FOUND: "Pickup location not found",
    DRIVER_FUTURE_ACCEPTED_ADDED:
      "Driver future booking accepted added successfully",
    DRIVER_CLAIMED_LIST: "Driver claimed list fetched successfully",
    TRIP_INFO: "Here is the trip info.",
    DRIVER_BALANCE: "Here is driver balance",
    DRIVER_LOCATION_NOT_FOUND:"Driver location not found"
  },
  BOOKING: {
    BOOKING_ADDED: "Booking added successfully",
    BOOKING_NOT_FOUND: "Booking not found",
    BOOKING_DELETED: "Booking soft-deleted",
    BOOKING_DETAIL: "Booking detail added successfully",
    BOOKING_UPDATED: "Booking updated successfully",
    BOOKING_STATUS_UPDATED: "Booking status updated successfully",
    BOOKING_STATUS_NOT_FOUND: "Booking status not found",
    BOOKING_STATUS_FETCHED: "Booking status fetched successfully",
    BOOKING_STATUS_NOT_FOUND: "Booking status not found",
    BOOKING_STATUS_UPDATED: "Booking status updated successfully",
    BOOKING_CANCELLED: "Booking cancelled successfully",
    BOOKING_STATUS_FAILED: "Booking status update failed",
    BOOKING_CANCELLED_FAILED: "Booking cancellation failed",
    BOOKING_HAS_CANCELLED: "Booking has been cancelled",
    BOOKING_CAN_ACCEPTED: "Booking can accepted.",
    BOOKING_FETCHED_INFO: "Booking info fetched successfully",
    BOOKING_ALREADY_ACCEPTED: "Booking already accepted",
    BILL_ALREADY_GENERATED: "Bill already generated",
    BOOKING_CHARGES_INSERTED: "Booking charges inserted successfully",
    BOOKING_ID_NOT_FOUND: "Booking ID not found",
    BOOKING_ID_REQUIRED: "Booking ID is required",
    BOOKING_ACCEPTED_SUCCESSFULLY: "Booking accepted successfully",
    NOT_VALID_RATING:"No valid fields provided for rating insertion",
    BOOKING_ALREADY_CANCELLED:"Already Cancelled Booking.",
    INVALID_RATING_VALUE:"Invalid rating values",
    MISSING_REQUIRED_FIELDS:"Missing required fields",
    INVALID_STATUS: "Invalid booking status",
    BOOKING_CANCELLATION_RULE: "Booking cancellation rule fetched successfully",
    BOOKING_CANCELLATION_RULE_NOT_FOUND: "Booking cancellation rule not found",
    BOOKING_CANCELLATION_RULE_UPDATED: "Booking cancellation rule updated successfully",
    BOOKING_CANCELLATION_RULE_ADDED: "Booking cancellation rule added successfully",
    BOOKING_CANCELLATION_RULE_DELETED: "Booking cancellation rule deleted successfully",
    BOOKING_CANCELLATION_RULE_FETCHED: "Booking cancellation rule fetched successfully",
    BOOKING_CANCELLATION_RULE_ALREADY_EXISTS: "Booking cancellation rule already exists",
  },
  LICENSE: {
    LICENSE_ADDED: "License added successfully",
    LICENSE_DELETED: "License soft-deleted",
    LICENSE_DETAIL: "License detail added successfully",
    LICENSE_UPDATED: "License updated successfully",
    LICENSE_KEY_NOT_FOUND: "License key not found",
    LICENSE_KEY_INVALID: "License key is invalid",
  },
};

export const ROLES = {
  ADMIN: "admin",
  USER: "user",
  CLIENT: "client",
};
