import { DataTypes } from "sequelize";
import sequelize from "../config/clientDbManager.js";

const ViewBookingList = sequelize.define(
  "vw_booking_list",
  {
    id: { type: DataTypes.INTEGER, primaryKey: true },
    base_vehicle_id: { type: DataTypes.INTEGER, allowNull: true },
    sac_code: { type: DataTypes.STRING, allowNull: true },
    sac_description: { type: DataTypes.TEXT, allowNull: true },
    flight_number: { type: DataTypes.STRING, allowNull: true },
    flight_time: { type: DataTypes.STRING, allowNull: true },
    vehicle_type_id: { type: DataTypes.INTEGER, allowNull: true },
    master_package_id: { type: DataTypes.INTEGER, allowNull: false },
    module_type: { type: DataTypes.TINYINT, allowNull: true },
    pickup_type: { type: DataTypes.STRING, allowNull: true },
    itinerary_id: { type: DataTypes.STRING, allowNull: true },
    company_id: { type: DataTypes.INTEGER, allowNull: false },
    status_c: { type: DataTypes.INTEGER, allowNull: true },
    status_id: { type: DataTypes.INTEGER, allowNull: false },
    status_name: { type: DataTypes.TEXT, allowNull: true },
    booking_date: { type: DataTypes.DATEONLY, allowNull: true },
    booking_time: { type: DataTypes.TIME, allowNull: true },
    booking_date_time: { type: DataTypes.DATE, allowNull: true },
    booking_release_date: { type: DataTypes.STRING(24), allowNull: true },
    pickup_date: { type: DataTypes.DATEONLY, allowNull: true },
    pickup_time: { type: DataTypes.TIME, allowNull: true },
    ordertime: { type: DataTypes.STRING, allowNull: true },
    pickup_area: { type: DataTypes.STRING, allowNull: true },
    departure: { type: DataTypes.STRING, allowNull: true },
    drop_area: { type: DataTypes.STRING, allowNull: true },
    drop_address: { type: DataTypes.STRING, allowNull: true },
    pickup_country: { type: DataTypes.STRING, allowNull: true },
    pickup_state: { type: DataTypes.STRING, allowNull: true },
    pickup_city: { type: DataTypes.STRING, allowNull: true },
    pickup_latitude: { type: DataTypes.STRING, allowNull: true },
    pickup_longitude: { type: DataTypes.STRING, allowNull: true },
    pickup_zone: { type: DataTypes.STRING, allowNull: true },
    drop_date: { type: DataTypes.DATEONLY, allowNull: true },
    drop_time: { type: DataTypes.TIME, allowNull: true },
    drop_country: { type: DataTypes.STRING, allowNull: true },
    drop_state: { type: DataTypes.STRING, allowNull: true },
    drop_city: { type: DataTypes.STRING, allowNull: true },
    drop_latitude: { type: DataTypes.STRING, allowNull: true },
    drop_longitude: { type: DataTypes.STRING, allowNull: true },
    drop_zone: { type: DataTypes.STRING, allowNull: true },
    user_id: { type: DataTypes.INTEGER, allowNull: true },
    user_name: { type: DataTypes.STRING, allowNull: true },
    user_email: { type: DataTypes.STRING, allowNull: true },
    user_mobile: { type: DataTypes.STRING, allowNull: true },
    user_alt_mobile: { type: DataTypes.STRING, allowNull: true },
    gst_registration_number: { type: DataTypes.STRING, allowNull: true },
    user_nationality: { type: DataTypes.STRING, allowNull: true },
    client_id: { type: DataTypes.INTEGER, allowNull: true },
    client_name: { type: DataTypes.STRING, allowNull: true },
    client_email: { type: DataTypes.STRING, allowNull: true },
    client_mobile: { type: DataTypes.STRING, allowNull: true },
    client_wallet: { type: DataTypes.DECIMAL(10, 0), allowNull: true },
    client_alt_mobile: { type: DataTypes.STRING, allowNull: true },
    driver_id: { type: DataTypes.INTEGER, allowNull: true },
    driver_name: { type: DataTypes.STRING, allowNull: true },
    driver_mobile: { type: DataTypes.STRING, allowNull: true },
    duty_status: { type: DataTypes.TINYINT, allowNull: true },
    user_role: { type: DataTypes.STRING, allowNull: true },
    driver_vehicle_type: { type: DataTypes.STRING, allowNull: true },
    vehicle_category_id: { type: DataTypes.INTEGER, allowNull: true },
    vendor_id: { type: DataTypes.INTEGER, allowNull: true },
    vendor_name: { type: DataTypes.STRING, allowNull: true },
    vendor_mobile: { type: DataTypes.STRING, allowNull: true },
    vendor_role: { type: DataTypes.STRING, allowNull: true },
    booking_estimation_id: { type: DataTypes.INTEGER, allowNull: true },
    amount: { type: DataTypes.INTEGER, allowNull: true },
    discount_price: { type: DataTypes.INTEGER, allowNull: true },
    total_tax_price: { type: DataTypes.INTEGER, allowNull: true },
    estimateprice_before_discount: { type: DataTypes.INTEGER, allowNull: true },
    approx_distance_charge: { type: DataTypes.DOUBLE, allowNull: true },
    booking_amt_percentage: { type: DataTypes.INTEGER, allowNull: true },
    service_charge: { type: DataTypes.STRING, allowNull: true },
    rounding: { type: DataTypes.STRING, allowNull: true },
    night_rate_value: { type: DataTypes.INTEGER, allowNull: true },
    night_charge_price: { type: DataTypes.INTEGER, allowNull: true },
    booking_amt_paid: { type: DataTypes.DOUBLE, allowNull: true },
    booking_amt_balance: { type: DataTypes.DOUBLE, allowNull: true },
    payment_type: { type: DataTypes.STRING, allowNull: true },
    is_paid: { type: DataTypes.TINYINT, allowNull: true },
    paid_at: { type: DataTypes.DATE, allowNull: true },
    vehicle_no: { type: DataTypes.STRING, allowNull: true },
    year: { type: DataTypes.STRING, allowNull: true },
    color: { type: DataTypes.STRING, allowNull: true },
    vehicle_name: { type: DataTypes.STRING, allowNull: true },
    domain_name: { type: DataTypes.STRING, allowNull: true },
    gst_no: { type: DataTypes.STRING, allowNull: true },
    currency_id: { type: DataTypes.INTEGER, allowNull: true },
    currency: { type: DataTypes.STRING, allowNull: true },
    currency_symbol: { type: DataTypes.STRING, allowNull: true },
    driver_share_amt: { type: DataTypes.INTEGER, allowNull: true },
    comp_share_amt: { type: DataTypes.INTEGER, allowNull: true },
    partner_share_amt: { type: DataTypes.INTEGER, allowNull: true },
    local_pkg_name: { type: DataTypes.STRING, allowNull: true },
    city_name: { type: DataTypes.STRING, allowNull: true },
  },
  {
    tableName: "vw_booking_list",
    timestamps: false,
    freezeTableName: true,
  }
);

export default ViewBookingList;
