export const clientNames = [
  "Maheshbhai Panchani",
  "Pushkar Joshi",
  "Sunny darpan travels",
  "Ramesh Gupta",
  "Bhagmal Sharma",
  "Praveen Rustagi",
  "Azad kataria",
  "Burrak Hashmi",
  "Manish kumar",
  "Kitesh Kumar Sharma",
  "BIJENDER Singh",
  "NIKHIL KANT",
  "PRADEEP TAWAR",
  "JIVAN SINGH",
  "DEEPAK RANA",
  "SANJEEV KUMAR YADAV",
  "SANJAY VERMA",
  "JYOTI BHUDDIRAJA",
  "SANTHOSH E",
  "Ashish Tomar",
  "ABHISHEK KUMAR",
  "BALA KRISHAN",
  "Suresh s",
  "Akash Meet",
  "Soloni richtravels",
  "MOHIT JAIN",
  "JEET J SORATHIYA",
  "VISHNU Tomar",
  "GAJRAJ SINGH BHADOURIYA",
  "Abhimanyu Sharma",
  "Gurmeet Singh",
  "Anurag Srivastava",
  "prashant patel",
  "bvnvcnvc123 xzvcxzvcxzvcx1233",
];

export const vehicleTypeLabels = [
  "Hatch Back (Tata Indica, Alto, Wagon R ...)",
  "Comfort Sedan (Maruti Swift Dzire, Tata Indigo, Mahindra Logan ...)",
  "Prime Compact (Toyota Innova, Mahindra Xylo, Maruti Ertiga ...)",
  "Prime (Innova Crysta (Bucket), Mahindra Marazzo, Mahindra XUV 500 ...)",
  "Sedan (Honda City, SX4, Ciaz ...)",
  "Prime Plus (Toyota Fortuner, Mitsubishi Pajero, MG Hector ...)",
  "Prime SUV Plus (Audi Q7(New), Audi Q7 ...)",
  "Premium Sedan  (Toyota Corolla, Toyota Altis, Honda Accord ...)",
  "Luxury Sedan (Mercedes Benz E Class, BMW 3 Series, Audi A4 ...)",
  "Luxury Sedan II (BMW 5 Series, Audi A6, Jaguar XE ...)",
  "Super Luxury Sedan (BMW 7 Series, Jaguar XF, Mercedes Benz S350D ...)",
  "Super Luxury Sedan II (Mercedes Benz S Class, BMW, BMW 720 ...)",
  "Compact MUV ( ...)",
  "Luxury SUV (Ford Endeavour, Range Rover Vogue Extended Wheelbase(Black), BMW X7 ...)",
  "Deluxe Van (9 Seats) (Tempo Traveller (DLX 9 Seats), Tempo Traveller ...)",
  "Luxury Van (Toyota Hiace (10 Seater), Mercedes Viano, Foton Traveller ...)",
  "Luxury Van Plus (Mercedes VIANO, Toyota Vellfire ...)",
  "Mini Coach (9 Seats) (Winger (9 seats), Force Urbania, Tempo Traveller ...)",
  "Mini Coach (12 Seats) (Tempo Traveller (12 Seater), Tempo Traveller (12 Seats PKN), Force Urbania ...)",
  "Mini Coach (16 Seater) (Tempo Traveller (17 Seater), Tempo Traveller (16 Seats PKN), TEMPO 18 SEATER ...)",
  "Mini Coach ( 20 Seater) (Tempo Traveller (20 Seater), Mini Coach (21 Seat), Mini Bus (18 Seat) ...)",
  "Mini Coach (27 Seats) (Bharat Benz (27 Seats), DLX Coach (27 Seats), Tempo Traveller (25 Seats PKN) ...)",
  "Deluxe Coach (35 Seater) (Marcopolo Deluxe Coach 35 Seater, Deluxe Coach 32 Seater, Bharat Benz (33 Seat) ...)",
  "Deluxe Coach (41 Seats) (Bus 41 Seater, Mercedes Benz Coach, Volvo Coach ...)",
  "Mini Coach (12 Seater) ( ...)",
  "Luxury Coach (45 Seater) (Volvo Coach (45 Seater), Mercedes Coach, Volvo with Toilet (45 Seater) ...)",
  "Super Cars (Rolls Royce, Rolls-Royce Phantom, Rolls-Royce Spectre ...)",
  "Deluxe Coach (27 Seats) ( ...)",
];

export const states = ["Delhi", "UP", "Haryana"];

export const countries = ["India", "USA", "UK"];

export const vehicleTypes = [
  { value: "1", label: "Hatch Back" },
  { value: "2", label: "Comfort Sedan" },
  { value: "3", label: "Prime Compact" },
  { value: "21", label: "Prime" },
  { value: "12", label: "Sedan" },
  { value: "22", label: "Prime Plus" },
  { value: "31", label: "Prime SUV Plus" },
  { value: "4", label: "Premium Sedan" },
  { value: "6", label: "Luxury Sedan" },
  { value: "7", label: "Luxury Sedan II" },
  { value: "8", label: "Super Luxury Sedan" },
  { value: "9", label: "Super Luxury Sedan II" },
  { value: "13", label: "Compact MUV" },
  { value: "10", label: "Luxury SUV" },
  { value: "11", label: "Luxury Van" },
  { value: "14", label: "Luxury Van Plus" },
  { value: "30", label: "Mini Coach (9 Seats)" },
  { value: "28", label: "Mini Coach (12 Seats)" },
  { value: "25", label: "Mini Coach (16 Seater)" },
  { value: "24", label: "Mini Coach (20 Seater)" },
  { value: "26", label: "Mini Coach (27 Seats)" },
  { value: "19", label: "Deluxe Coach (35 Seater)" },
  { value: "27", label: "Deluxe Coach (41 Seats)" },
  { value: "20", label: "Luxury Coach (45 Seater)" },
  { value: "39", label: "Super Cars" },
];


export const indianStates = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli",
  "Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kenmore",
  "Kerala",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Narora",
  "Natwar",
  "Odisha",
  "Paschim Medinipur",
  "Pondicherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "Vaishali",
  "West Bengal",
];

export const bookingStatus = [
 { value: "1", label: "Registered" },
  { value: "2", label: "Processing" },
  { value: "3", label: "Accepted" },
  { value: "4", label: "Located" },
  { value: "5", label: "Reported" },
  { value: "6", label: "On Wait" },
  { value: "7", label: "On Trip" },
  { value: "8", label: "Trip Done" },
  { value: "9", label: "Rejected" },
  { value: "10", label: "Driver Cancel" },
  { value: "11", label: "Paid" },
  { value: "15", label: "Rejected" }, // duplicate label, different value
  { value: "12", label: "Credit" },
  { value: "13", label: "Manually Assign" },
  { value: "14", label: "No Show Bookings" },
  { value: "16", label: "Dispose by CC" },
  { value: "17", label: "cancel by CC" },
  { value: "18", label: "All" },
  { value: "19", label: "Expired" },
  { value: "20", label: "Client Cancel" },
  { value: "21", label: "Vendor Cancel" },
  { value: "23", label: "Getting Late" },
  { value: "24", label: "Break Down" },
  { value: "25", label: "Wrong Address" },
  { value: "26", label: "Other" },
  { value: "22", label: "Hold" },
  { value: "27", label: "Quotation" },
  { value: "28", label: "Shopping Cart" },
  { value: "29", label: "No Cab Available" },
  { value: "30", label: "Non Payment" },
];

export const ignitionType = [
  { id: "1", label: "Petrol" },
  { id: "2", label: "Diesel" },
  { id: "3", label: "CNG" },
  { id: "4", label: "Electric" },
  { id: "5", label: "Solar" },
  { id: "6", label: "Methanol" }
]

export const vehicleColor = [
  "White",
  "Black",
  "Maroon",
  "Gray",
  "Silver",
  "Blue",
  "Red",
  "Brown",
  "Gold",
  "Green",
  "Dark Brown",
  "Orange",
  "Purple",
  "Yellow",
  "Sky Blue",
];


export const amenities = [
  "Automatic Transmission",
  "Manual Transmission",
  "Air Conditioning",
  "Automatic Cooling",
  "Carrier",
  "Water Bottle",
  "Tissue Box",
  "Washroom",
  "Baby Sitting",
  "Music System",
  "Mobile & Laptop Charger",
  "News Paper",
  "Fire Extinguisher",
  "Air Pump",
  "Chillar",
  "Oxygen Cylinder"
]



export const voucherTypes = [
  "ADJUSTMENT VOUCHER( ADJ)",
  "BANK PAYMENT VOUCHER( BPV)",
  "BANK PAYMENT VOUCHER AUD( BAV)",
  "BANK PAYMENT VOUCHER USD( BUV)",
  "BANK RECEIPT VOUCHER( BRV)",
  "CASH PAYMENT VOUCHER( CPV)",
  "CASH RECEIPT VOUCHER( CRV)",
  "CONTRA ENTRY AUD( COA)",
  "CONTRA ENTRY EUR( COE)",
  "CONTRA ENTRY INR( CON)",
  "CONTRA ENTRY USD( COD)",
  "FLUCTUATE RATE OF EXCH.( FRE)",
  "JOURNAL VOUCHER( JUR)",
  "OUTBOUND RECEIPT( IBN)",
  "OUTBOUND PAYMENT-AUD( OBA)",
  "OUTBOUND PAYMENT-EUR( OBE)",
  "OUTBOUND PAYMENT-GBP( OBP)",
  "OUTBOUND PAYMENT-USD( OBD)",
  "OUTBOUND RECEIPT-AUD( IBA)",
  "OUTBOUND RECEIPT-EUR( IBB)",
  "OUTBOUND RECEIPT-GBP( IBP)",
  "OUTBOUND RECEIPT-HKD( IBH)",
  "OUTBOUND RECEIPT-USD( IBR)",
  "POST DATED CHEQUE( PDC)"
];