import Head from "next/head";

export default function TermsAndConditions() {
  const companyName = process.env.NEXT_COMPANY_NAME;
  return (
    <>
      <Head>
        <title>Terms & Conditions | {companyName}</title>
        <meta
          name="description"
          content={`Terms & Conditions for using ${companyName} services`}
        />
      </Head>
      <main className="max-w-4xl mx-auto px-8 pt-10 text-justify text-gray-800 sm:px-12 mt-10 mb-20">
        <h1 className="text-2xl font-bold mb-6 sm:text-3xl">Terms & Conditions</h1>

       <p className="mb-4 text-sm">
          This document is an electronic record in terms of Information
          Technology Act, 2000 and rules there under as applicable and the
          amended provisions pertaining to electronic records in various
          statutes as amended by the Information Technology Act, 2000. This
          electronic record is generated by a computer system and does not
          require any physical or digital signatures. These terms and conditions
          (Service-User terms) apply on the usage of our website www.
          {companyName}.com & www.{companyName}.com (the "Website"), smart phone {" "}
          {companyName}, {companyName} Application (the Application) as well as
          to all information, recommendations and/or services provided to you on
          or through the Website, the Application or through the Customer Care
          (The CC) through a national phone number (City code 011 )– 42424242 &
          47474747. The term 'YOU' refers to the user of our services through
          Website, the Application and the CC. The terms and conditions
          mentioned in this contract along with the Privacy Policy constitute
          the entire contract between the User(s) and {companyName} with respect
          to access to and use of the website / application and the Services
          offered by {companyName}, superseding any prior written or oral
          contracts in relation to the same subject matter herein.
        </p>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">THE SERVICE</h2>
          <p className="mb-2 text-sm">
            {companyName} offers a technology platform on Website, Call center
            and Mobile Application {companyName} available on Android platform
            and IOS.
          </p>
         <p className="mb-2  text-sm">
            {companyName}'s Technology platform is an enabling platform for a
            consumer to connect with a third party, independent valid permit
            holder drivers or vehicle operators known as The Transport Service
            Provider hereinafter referred as TSP. Once TSP accepts a request,
            customer is notified with the details of TSP through sms or Mobile
            application. {companyName} shall do all the reasonable efforts to
            connect you with a TSP & the services are subject to the
            availability of TSPs in or around your location at the moment of
            your request or services required for transportation services. By
            using this website and/or Mobile Application or user of the service
            through The CC you hereby acknowledges that ({companyName}) is not a
            transport services provider. It is up to the TSP to offer
            transportation services, which may be requested through the use of
            the Website, Application or CC. {companyName} only acts an
            intermediary between you and the TSP. The user has to note that TSP
            is your service provider and therefore it is subjected to the
            contract between YOU and the TSP. {companyName} shall never be a
            party to such contract. {companyName} operates full-day, Point to
            Point , Airport Transfers, intercity and Out station, Bus booking
            requests.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">USER(S) ELIGIBILITY</h2>
         <p className="mb-2 text-sm">
            User(s) means any individual or business entity/organization that
            legally operates in India or in other countries, uses and has the
            right to use the Services provided by {companyName}. Our Services
            are available only to those individuals or companies who can form
            legally binding contracts under the applicable law. Therefore,
            user(s) must not be a minor as per Indian Law; i.e. user(s) must be
            at least 18 years of age to be eligible to use our Services.
            {companyName} advises its users that while accessing the web site/
            the application, they must follow/abide by the related laws.{" "}
            {companyName}
            is not responsible for the possible consequences caused by your
            behavior during use of web site/application. {companyName} at all
            the times reserves the right to deny service.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">
            USER ACCOUNTS, OFFERS AND PROMOTIONS
          </h2>
          <p className="mb-2  text-sm">
            {companyName} collects general user data including name, email ID,
            contact details etc. to facilitate services. It is assumed that all
            information collected from the user is Correct & Accurate. Misuse
            and misrepresentation of identity or contact details will lead to
            automated termination of services or the use of the platform without
            prior notice to such users. User accounts bearing contact number and
            email IDs are created and owned by {companyName}. Any promotional
            discounts, offers and reward points in the form of {companyName}{" "}
            Money accumulated can be revoked without prior notice in the event
            of suspicious account activity or malafide intention of the user. In
            the case where the system is unable to establish unique identity of
            the user against a valid mobile number or e-mail ID, the account
            shall be indefinitely suspended. {companyName} reserves the full
            discretion to suspend a user's account, the above event and does not
            have the liability to share any account information whatsoever.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">Usage Conditions</h2>
          <ul className="list-disc list-inside space-y-1  text-sm sm:text-base xl:text-base">
            <li className="text-sm">
              You understand your contract with {companyName} for Website,
              Application, and Customer Care (CC) usage, and you acknowledge the
              SERVICE along with the provided CLARIFICATIONS.
            </li>
            <li className="text-sm">
              You will use the Application for personal purposes only and not
              for resale (in the case of individuals).
            </li>
            <li className="text-sm">
              You will not assign or transfer your account to any other person
              or legal entity.
            </li>
            <li className="text-sm">
              You will not use the Service or Application for any unlawful
              purposes, including but not limited to sending or storing unlawful
              material or engaging in fraudulent activities.
            </li>
            <li className="text-sm">You will not impair the proper operation of the network.</li>
            <li className="text-sm">
              You will not attempt to harm the Service or Application in any
              way.
            </li>
            <li className="text-sm">
              You will not copy or distribute the Application or any other
              {companyName} content without written permission from{" "}
              {companyName}.
            </li>
            <li className="text-sm">
              You will keep your account information and any identification
              provided to access the Service and Application confidential, and
              you will not share this information with anyone else.
            </li>
            <li className="text-sm">
              You will provide us with any reasonable proof of identity upon
              request.
            </li>
            <li className="text-sm">
              You will comply with all applicable laws in your city, state, and
              country while using the Application or Service.
            </li>
          </ul>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">
            GENERAL CUSTOMER BEHAVIOUR WHILE USING TRANSPORT SERVICE
          </h2>
          <p className="mb-2  text-sm">
            {companyName} expect good behavior from their customer/user while
            using the TSP services. {companyName} encourages its entire customer
            to take care of their items. In case of any lost while using the
            services of {companyName}, company will try to locate and find out
            the item but {companyName} are not responsible for any damage or
            loss while using {companyName} services. All the calls made to the
            Company's CC are recorded by the Company for quality and training
            purposes. The customer shall ensure that he/she will not indulge in
            any of the following activities while in a Cab like asking driver to
            overload the space of the cab luggage or break the traffic rules.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">
            REPRESENTATION, WARRANTIES, INDEMNIFICATION AND LIMITATION OF
            LIABILITY
          </h2>
         <p className="mb-2  text-sm">
            Without prejudice to the above, the Company makes no representation
            or warranties that: The Services will meet the customer's
            requirements. The Services will be uninterrupted, timely or
            error-free. {companyName} shall not be responsible or liable for any
            loss or damage, howsoever caused or suffered by the Customer arising
            out of the use of Cab service offered by TSP or due to the failure
            of TSP to provide Services to the Customer for any reason whatsoever
            including but not limited to the Customer's non-compliance with the
            Services' recorded voice instructions, malfunction, partial or total
            failure of any network terminal, data processing system, computer
            tele-transmission or telecommunications system or other
            circumstances whether or not beyond the control of Company or any
            person or any organization involved in the above mentioned systems.
            {companyName} will not be liable for any damages of any kind arising
            from the use of the Service offered by the TSP including, but not
            limited to direct, indirect, incidental, punitive, and consequential
            damages. {companyName} will take all reasonable measures to ensure
            that TSP should fulfill his duty properly but there may be
            exceptions and if any passenger misses the train or flight or bus,
            {companyName} will not be held liable for any such compensation. The
            customer is advised to make the booking taking care of Time gap &
            alternate arrangement in case the cab has not reached due to any
            reason. The Company shall not be liable for any conduct of the
            drivers of the Cabs. {companyName} encourages you to notify any
            complaints that you may have against the driver of any Cab that you
            may have hired using the {companyName}'s platform. All the vehicles
            registered with {companyName} platform are continuously tracked
            using GPS for security reasons only. It is expressly made clear to
            you hereby that the Company does not own any Cabs nor
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">
            AMENDMENT TO TERMS OF CONTRACT
          </h2>
          <p className="mb-2  text-sm">
            The {companyName} shall be entitled to add , vary or amend any or
            all these terms and conditions at any time and the Customer shall be
            bound by such addition, variation or amendment once such addition,
            variation or amendment are incorporated into these terms and
            conditions at Company's website at www.{companyName}.com or the
            Application on the date that Company may indicate that such
            addition, variation or amendment is to come into effect.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">
            INTELLECTUAL PROPERTY RIGHTS
          </h2>
          <p className="mb-2  text-sm">
            {companyName} is the sole owner or lawful licensee of all the rights
            to the web site, Application and its content. Web site content means
            its design, layout, text, images, graphics, sound, video etc. The
            web site content embodies trade secrets and intellectual property
            rights protected under worldwide copyright and other laws. All
            rights not otherwise claimed under this contract or by www.
            {companyName}.com, are hereby reserved. The information contained in
            this web site is intended, solely to provide general information for
            the personal use of the reader, who accepts full responsibility for
            its use. {companyName} reserves the right, in its sole discretion
            and without any obligation, to make improvements to, or correct any
            error or omissions in any portion of the Service or the website.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">TRADEMARK</h2>
         <p className="mb-2  text-sm">
            All related icons and logos are registered trademarks or trademarks
            or service marks of {companyName} in various jurisdictions and are
            protected under applicable copyright, trademark and other
            proprietary rights laws. The unauthorized copying, modification, use
            or publication of these marks is strictly prohibited.
          </p>
        </section>
      </main>
    </>
  );
}
